version: '3.8'

services:
  db:
    image: postgres:16.0
    restart: always
    container_name: urbansky-inventory-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGPORT: ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
  api:
    platform: linux/amd64
    container_name: urbansky-inventory-api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./api/src:/usr/src/app/src:consistent
    ports:
      - ${API_PORT}:${API_PORT}
      #- 9230:9230
